apiVersion: v1
kind: Service
metadata:
  name: health-backend
spec:
  selector:
    app: health-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: health-frontend
spec:
  selector:
    app: health-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
